name: Build Lumia Rift ARM32
on:
  push:
    paths:
      - "LumiaRiftPSP/**"
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        working-directory: LumiaRiftPSP
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - name: Build game
        shell: pwsh
        run: .\Build-All.ps1 -Configuration Release -SkipPsp
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: Lumia-Rift-ARM32
          path: LumiaRiftPSP/artifacts/*
          if-no-files-found: error
